version: '3'

name: uomi

services:
    laravel:
        build: 
          context: src
          dockerfile: ../docker/Dockerfile
        # image: ghcr.io/SDU-mobile-dev-2023-4/android-backend
        ports:
            - '${APP_PORT:-8080}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            DB_HOST: mysql
            DB_USERNAME: ${DB_USERNAME:-uomi}
            DB_DATABASE: ${DB_DATABASE:-uomi}
            DB_PASSWORD: ${DB_PASSWORD:-uomi}
            TZ: ${TIMEZONE}
        volumes:
            - ./src:/var/www/html
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit
        user: "${UID:-1000}:${GID:-1000}"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8080}"]
            retries: 3
            timeout: 5s
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-uomi}
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_DATABASE:-uomi}
            MYSQL_USER: ${DB_USERNAME:-uomi}
            MYSQL_PASSWORD: ${DB_PASSWORD:-uomi}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '${PHPMYADMIN_PORT:-8081}:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_ARBITRARY: 1
        networks:
            - sail
networks:
    sail:
        driver: bridge
    nginx-proxy:
        external: true

volumes:
    mysql:
        driver: local
